### ISSUE TITLE
应该判断系统类型,windows系统下不需添加`/`前缀到文件夹路径, 当前生成的路径示例/e:/projects/`

### ISSUE THREAD

**Issue by RobertWu-TIBCO** [SaekiRaku/vscode-pin-up#1]
installed on win10 G 企业版+vscode 

将工作区文件夹`pin up`后, 使用时,提示,文件夹不存在`/e:/projects/`

应该判断系统类型,windows下不需添加`/`前缀.

具体系统和vscode信息:

[Window Title]
Visual Studio Code

[Main Instruction]
Visual Studio Code

[Content]

版本: 1.44.2 (system setup)
提交: ff915844119ce9485abfe8aa9076ec76b5300ddd
日期: 2020-04-16T16:36:23.138Z (2 周前)
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.15063

**Comment by SaekiRaku** [comment]
感谢反馈，BUG 已修复并推送新版本。微软扩展商店审核仍需一段时间（约 1 小时左右）。
