### ISSUE TITLE
Feature request: settings to ignore and hide files

### ISSUE THREAD

**Issue by robertoentringer** [SaekiRaku/vscode-pin-up#10]
It would be nice if the settings panel provides an input to enter the files or folder to be ignored.
Example :  .git repository folder

**Comment by SaekiRaku** [comment]
Thanks for your advice. This feature is added with the new release of `1.4.0`.

You can use the setting of `pin-up.list.ignore` (array) to hide files or folders on the pinned list by RegExp.

For example (default): 

```json
// VSCode settings.json
{
    "pin-up.list.ignore": [
        "\\.git/"
    ]
}
```

**Comment by robertoentringer** [comment]
Thank you 🎉🎉🎉.

**Comment by devalnor** [comment]
Unfortunately this feature seams not to work for me.
`.git` folders are still visibles. All settings are defaults.
The only difference is that I use workspaces.

I also tried with this:
```json
// VSCode settings.json
{
    "pin-up.list.ignore": [
        "\\.git/",
        "\\.DS_Store/"
     ]
}
```
