### ISSUE TITLE
Suggestion : Remove duplicate arrows for more concise layout

### ISSUE THREAD

**Issue by robertoentringer** [SaekiRaku/vscode-pin-up#12]
![Capture d’écran 2020-10-02 à 15 58 56](https://user-images.githubusercontent.com/1759811/94932232-15772700-04c9-11eb-9aa1-a16767baa7ff.png)

**Comment by SaekiRaku** [comment]
Hi, sorry for my slowly respond, I just finished my holiday of National Day.

First of all, thanks for your feedback. But I think there is nothing I can do for this issue. The left arrow is provided by the `VSCode Tree View`, the right triangle is provided by the `VSCode Theme Icon`, neither of them can be hidden by programming. But you can hide the `Theme Icon` on the `Settings` of `workbench.iconTheme`.

I think it is your VSCode is using a theme icon that leads to display the triangle at the right. Try setting the `workbench.iconTheme` to `vs-minimal` and see if it will be fixed. Or I recommend using a nice `Theme Icon`(such as [vscode-icons](https://marketplace.visualstudio.com/items?itemName=vscode-icons-team.vscode-icons)) to gain a better visual experience of the Tree View. Like below:

<img width="254" alt="QQ20201009-205445@2x" src="https://user-images.githubusercontent.com/12109558/95585357-b2aa0080-0a71-11eb-855c-41fb58189648.png">

Reference:
- [VSCode TreeItem API](https://code.visualstudio.com/api/references/vscode-api#TreeItem) at iconPath property.

**Comment by robertoentringer** [comment]
Hi, thanks for your reply! Indeed with the vs-minimal theme icon there are no more double arrows!
The double arrows are probably linked to the theme I use : Monokai PRO.
