### ISSUE TITLE
考虑追加一个pin非当前项目文件的功能么

### ISSUE THREAD

**Issue by kuangyanit** [SaekiRaku/vscode-pin-up#4]
目前是通过手动hack（在json里自己追加路径)来处理这个需求的，希望可以支持pin非当前项目文件的功能。。

**Comment by SaekiRaku** [comment]
我发布了一个新版本，现在可以从工作区外部钉住文件了。
I've published a new release that now you can pin up files from outside of the workspace.
<img width="369" alt="QQ20200529-113602@2x" src="https://user-images.githubusercontent.com/12109558/83218680-ffff9280-a1a0-11ea-8614-94d032de53e0.png">
