### ISSUE TITLE
考虑支持在pin目录后在该目录下新建文件(或目录)么？

### ISSUE THREAD

**Issue by kuangyanit** [SaekiRaku/vscode-pin-up#5]

**Comment by SaekiRaku** [comment]
Good Idea, 我着手看一下。

**Comment by SaekiRaku** [comment]
新版本发布 v1.2.0，为固定列表增加新建文件目录和删除功能。

变更日志：
- Added: Create file/folder and delete it in Pinned List.
- Fixed: Add category property to each commands.

**Comment by kuangyanit** [comment]
dalao神速。想问下另个问题，目前这个版本的新建是会弹出一个框然后填写，这个形式可以跟vscode自带的新建形式保持一致么?

**Comment by SaekiRaku** [comment]
> 目前这个版本的新建是会弹出一个框然后填写，这个形式可以跟vscode自带的新建形式保持一致么?

@kuangyanit 目前来看无法实现，VSCode 的侧边栏是通过 TreeView 对象实现的，限制比较多，只能做一些很基本的呈现&操作。包括我目前使用的一些非官方的 Extension 也没有看到过可以实现和 VSCode Explorer 侧边栏一模一样的交互的。P.S. 如果有就可以直接抄源码了😂。

**Comment by kuangyanit** [comment]
> > 目前这个版本的新建是会弹出一个框然后填写，这个形式可以跟vscode自带的新建形式保持一致么?
> 
> @kuangyanit 目前来看无法实现，VSCode 的侧边栏是通过 TreeView 对象实现的，限制比较多，只能做一些很基本的呈现&操作。包括我目前使用的一些非官方的 Extension 也没有看到过可以实现和 VSCode Explorer 侧边栏一模一样的交互的。P.S. 如果有就可以直接抄源码了😂。

明白了。感谢解答。
