### ISSUE TITLE
Ability to distinguish pins

### ISSUE THREAD

**Issue by msaspence** [SaekiRaku/vscode-pin-up#7]
I often pin two or more directories that have the same name. For example one is `components/myThing` and the other is `ducks/myThing`, this seems like a common use case since Pin Up is great for pinning closely related code in desperate parts of the code base.

It would be cool if there was a way to easily distinguish these. Either automatically by prefixing the location of the directory to root items, maybe in a similar way that directories with a single child can be collapsed. Or manually by giving pins a name when you create them.

**Comment by SaekiRaku** [comment]
Hi, thanks for your feedback! I've added something to the new release of v1.3.0, please try it out and let me know if it suits your need.

Now you can right-click the pinned files and set `alias` for each of them. And by default, it will use the parent directory name if there have duplicated name of the pinned files (Currently, it have bugs on windows, I will fix it after I set up my virtual machine to debug it).
