### ISSUE TITLE
FR: Confirmation window when deleting a pin

### ISSUE THREAD

**Issue by ioandev** [SaekiRaku/vscode-pin-up#8]
Hi,

Great extension, especially that you can add folders outside the current project.

Could you add an option for having a confirmation window _Are you sure you want to delete this pin?_ when clicking the delete button?

Ioan

**Comment by SaekiRaku** [comment]
Hi, thanks for your advice. I've added this improvement to version 1.3.2. Now, you can use the setting of `pin-up.confirm.removePin` to control if display a confirmation window before remove or clear the pins.
